# Meta Data for SEO

## Homepage
title = "APK Lab"
titleSeparator = "-"
titleAddition = "Android Reverse Engineering WorkBench for VS Code"
description = "The ultimate Android RE experience right inside your VS Code."

## Open Graph + Twitter Cards
images = ["logo.svg"]
# twitterSite = "henkverlinde"
# twitterCreator = "henkverlinde"
# facebookAuthor = "verlinde.henk"
# facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
# schemaTwitter = "https://twitter.com/henkverlinde"
# schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/Surendrajat/APKLab"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like APKLab? <a class=\"alert-link\" href=\"https://github.com/Surendrajat/APKLab\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/Surendrajat/docs"
editPage = true
