# Meta Data for SEO

## Homepage
title = "APKLab"
titleSeparator = "-"
titleAddition = "Android Reverse Engineering WorkBench for VS Code"
description = "The ultimate Android RE experience right inside your VS Code."

## Open Graph + Twitter Cards
images = ["logo.svg"]
# twitterSite = "henkverlinde"
# twitterCreator = "henkverlinde"
# facebookAuthor = "verlinde.henk"
# facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaGitHub = "https://github.com/APKLab/APKLab"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footerLeft = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://getdoks.org/\">Doks</a>"
footerRight = "Made with 💓 in India"

# Alert
alert = false
alertText = "Like APKLab? <a class=\"alert-link\" href=\"https://github.com/APKLab/APKLab\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/APKLab/website"
editPage = false
