image: node:latest

test:
  script:
    - npm ci
    - npm run clean
    - npm run build
  except:
    - master

pages:
  script:
    - npm ci
    - npm run clean
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
